export const NODE_TYPES = [
  {
    type: 'input',
    label: 'Input',
    icon: 'import',
    color: '#6C5CE7',
    description: 'Receive input data for the workflow',
    defaultConfig: {
      inputType: 'text',
      required: true,
    },
  },
  {
    type: 'process',
    label: 'Process',
    icon: 'cog',
    color: '#00B894',
    description: 'Transform or process data',
    defaultConfig: {
      operation: 'transform',
    },
  },
  {
    type: 'decision',
    label: 'Decision',
    icon: 'swap-horizontal',
    color: '#FDCB6E',
    description: 'Make conditional decisions',
    defaultConfig: {
      condition: '',
    },
  },
  {
    type: 'api_call',
    label: 'API Call',
    icon: 'api',
    color: '#74B9FF',
    description: 'Make external API requests',
    defaultConfig: {
      method: 'GET',
      url: '',
    },
  },
  {
    type: 'ai_agent',
    label: 'AI Agent',
    icon: 'robot',
    color: '#A29BFE',
    description: 'Execute AI model operations',
    defaultConfig: {
      provider: 'openai',
      model: 'gpt-4',
    },
  },
  {
    type: 'output',
    label: 'Output',
    icon: 'export',
    color: '#FF6B6B',
    description: 'Return workflow results',
    defaultConfig: {
      outputType: 'json',
    },
  },
];

export const WORKFLOW_TEMPLATES = [
  {
    id: 'template_1',
    name: 'Data Processing Pipeline',
    description: 'Extract, transform, and load data from various sources',
    category: 'Data Processing',
    estimatedTime: '5',
    nodes: [
      {
        id: 'node_1',
        type: 'input',
        label: 'Data Source',
        position: { x: 50, y: 100 },
        config: { inputType: 'file' },
      },
      {
        id: 'node_2',
        type: 'process',
        label: 'Transform',
        position: { x: 200, y: 100 },
        config: { operation: 'transform' },
      },
      {
        id: 'node_3',
        type: 'output',
        label: 'Store Results',
        position: { x: 350, y: 100 },
        config: { outputType: 'database' },
      },
    ],
    connections: [
      { id: 'conn_1', from: 'node_1', to: 'node_2' },
      { id: 'conn_2', from: 'node_2', to: 'node_3' },
    ],
  },
  {
    id: 'template_2',
    name: 'Email Automation',
    description: 'Automated email campaigns with personalization',
    category: 'Communication',
    estimatedTime: '3',
    nodes: [
      {
        id: 'node_1',
        type: 'input',
        label: 'Contact List',
        position: { x: 50, y: 100 },
        config: { inputType: 'csv' },
      },
      {
        id: 'node_2',
        type: 'ai_agent',
        label: 'Personalize',
        position: { x: 200, y: 100 },
        config: { provider: 'openai', model: 'gpt-4' },
      },
      {
        id: 'node_3',
        type: 'api_call',
        label: 'Send Email',
        position: { x: 350, y: 100 },
        config: { method: 'POST', url: '/api/send-email' },
      },
    ],
    connections: [
      { id: 'conn_1', from: 'node_1', to: 'node_2' },
      { id: 'conn_2', from: 'node_2', to: 'node_3' },
    ],
  },
  {
    id: 'template_3',
    name: 'Content Analysis',
    description: 'Analyze and categorize content using AI',
    category: 'Analysis',
    estimatedTime: '4',
    nodes: [
      {
        id: 'node_1',
        type: 'input',
        label: 'Content Input',
        position: { x: 50, y: 100 },
      },
      {
        id: 'node_2',
        type: 'ai_agent',
        label: 'Analyze',
        position: { x: 200, y: 100 },
      },
      {
        id: 'node_3',
        type: 'decision',
        label: 'Categorize',
        position: { x: 350, y: 100 },
      },
      {
        id: 'node_4',
        type: 'output',
        label: 'Results',
        position: { x: 500, y: 100 },
      },
    ],
    connections: [
      { id: 'conn_1', from: 'node_1', to: 'node_2' },
      { id: 'conn_2', from: 'node_2', to: 'node_3' },
      { id: 'conn_3', from: 'node_3', to: 'node_4' },
    ],
  },
  {
    id: 'template_4',
    name: 'Social Media Bot',
    description: 'Automated social media posting and engagement',
    category: 'Automation',
    estimatedTime: '6',
    nodes: [
      {
        id: 'node_1',
        type: 'input',
        label: 'Topic Input',
        position: { x: 50, y: 100 },
      },
      {
        id: 'node_2',
        type: 'ai_agent',
        label: 'Generate Content',
        position: { x: 200, y: 100 },
      },
      {
        id: 'node_3',
        type: 'api_call',
        label: 'Post to Social',
        position: { x: 350, y: 100 },
      },
    ],
    connections: [
      { id: 'conn_1', from: 'node_1', to: 'node_2' },
      { id: 'conn_2', from: 'node_2', to: 'node_3' },
    ],
  },
];

export const SUBSCRIPTION_TIERS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    priceId: null,
    features: {
      maxWorkflows: 3,
      maxNodes: 10,
      apiCalls: 100,
      storage: '100MB',
      support: 'Community',
      analytics: false,
      collaboration: false,
    },
    limits: {
      workflows: 3,
      nodesPerWorkflow: 10,
      apiCallsPerMonth: 100,
      storageMB: 100,
    },
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 9.99,
    priceId: 'price_premium_monthly',
    popular: true,
    features: {
      maxWorkflows: 'Unlimited',
      maxNodes: 50,
      apiCalls: '10,000',
      storage: '10GB',
      support: 'Email',
      analytics: true,
      collaboration: false,
    },
    limits: {
      workflows: -1,
      nodesPerWorkflow: 50,
      apiCallsPerMonth: 10000,
      storageMB: 10240,
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 49.99,
    priceId: 'price_enterprise_monthly',
    features: {
      maxWorkflows: 'Unlimited',
      maxNodes: 'Unlimited',
      apiCalls: 'Unlimited',
      storage: '100GB',
      support: 'Priority',
      analytics: true,
      collaboration: true,
    },
    limits: {
      workflows: -1,
      nodesPerWorkflow: -1,
      apiCallsPerMonth: -1,
      storageMB: 102400,
    },
  },
];

export const API_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'robot',
    color: '#10A37F',
    keyFormat: 'sk-...',
    description: 'Access GPT-4, GPT-3.5, and other OpenAI models',
    signupUrl: 'https://platform.openai.com/signup',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: 'brain',
    color: '#D97706',
    keyFormat: 'sk-ant-...',
    description: 'Access Claude and other Anthropic models',
    signupUrl: 'https://console.anthropic.com/',
  },
  {
    id: 'google',
    name: 'Google AI',
    icon: 'google',
    color: '#4285F4',
    keyFormat: 'AIza...',
    description: 'Access Gemini and other Google AI models',
    signupUrl: 'https://makersuite.google.com/',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    icon: 'language-python',
    color: '#6C5CE7',
    keyFormat: 'oc-...',
    description: 'AgentForge platform API access',
    signupUrl: 'https://openclaw.io/signup',
  },
];

export const COLORS = {
  primary: '#6C5CE7',
  secondary: '#00B894',
  accent: '#FDCB6E',
  danger: '#FF6B6B',
  success: '#00B894',
  warning: '#FDCB6E',
  info: '#74B9FF',
  background: '#1a1a2e',
  surface: '#16213e',
  text: '#fff',
  textSecondary: '#8899A6',
  border: '#0f3460',
};